spring:
  application:
    name: ninja-cart-service
server:
  port: 60020

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
info:
  app:
    name: "default"
    desc: "default"
    version: "default"
